<a href="https://colab.research.google.com/github/Safwanarakkal/DBMS/blob/main/program3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

array_from_list = np.array([1, 2, 3, 4, 5])
print("Array from list:", array_from_list)

array_with_range = np.arange(10)
print("Array with range:", array_with_range)

zeros_array = np.zeros((3, 3))
print("Array of zeros:\n", zeros_array)

ones_array = np.ones((2, 5))
print("Array of ones:\n", ones_array)

Array from list: [1 2 3 4 5]
Array with range: [0 1 2 3 4 5 6 7 8 9]
Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array of ones:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
